justifi-tech/public-docs

- src/pages/index.tsx
I added the redirect to the gettingstarted page.  I also added a url rewrite for the incoming requests from developer.justifi.ai.
Closes #11
> Add Homepage Redirects

- docs/payments/compliance.mdx
Fixed the typo on the sidebar
Closes #13
> Sidebar Typo

- openapi/multi-yaml/components/schemas/AdditionalQuestions.yaml
ref justifi-tech/entity_management#107
> public-docs: add business additional questions

- openapi/multi-yaml/components/parameters/payment-method-group-id.yaml
- openapi/multi-yaml/components/schemas/PaymentMethodGroupResponse.yaml
- openapi/multi-yaml/index.yaml
- openapi/multi-yaml/paths/payment_method_groups.yaml
- openapi/multi-yaml/paths/payment_method_groups@{id}.yaml
- openapi/multi-yaml/paths/payment_methods.yaml
https://github.com/justifi-tech/public-docs/issues/21
> Add payment method groups docs

- openapi/docs/api_onboarding.md
- openapi/docs/hosted_onboarding.md
- openapi/multi-yaml/index.yaml
- fix: add ending back ticks and remove PullRight
- fix: remove reference to checkout sessions
> 36 fix hosted onboarding

- openapi/multi-yaml/components/schemas/Checkout.yaml
- openapi/multi-yaml/components/schemas/CheckoutCompletion.yaml
- openapi/multi-yaml/index.yaml
- openapi/multi-yaml/paths/checkouts.yaml
- openapi/multi-yaml/paths/checkouts@{id}.yaml
- openapi/multi-yaml/paths/checkouts@{id}@complete.yaml
- add: rough checkout docs
- add: checkouts to path
> add checkout section

- openapi/docs/description.md
- openapi/multi-yaml/paths/payments.yaml
- feat: add refernce to network_decline_code presence when card is declined
- fix: for platforms reference
> 859 add network decline code

- openapi/docs/description.md
Adds a new table to document possible network_error_code meaning returned in payfac error response (when available)
> feat: new table with network error codes, description, & customer impact

- openapi/docs/checkout.md
- openapi/docs/checkout_api.md
- openapi/docs/hosted_onboarding.md
- fix url in hosted onboarding
- Update checkout docs
> fix hosted onboarding and checkout docs

- docs/infrastructure/webComponentTokens.mdx
closes https://github.com/orgs/justifi-tech/projects/8/views/6?pane=issue&itemId=62143029
> fix: update guide for business form stepped to new name

- openapi/multi-yaml/events/payment_intents.yaml
- openapi/multi-yaml/index.yaml
- openapi/multi-yaml/paths/checkouts@{id}.yaml
- openapi/multi-yaml/paths/payment_intents.yaml
- openapi/multi-yaml/paths/payment_intents@{id}.yaml
- openapi/multi-yaml/paths/payment_intents@{id}@capture.yaml
- openapi/multi-yaml/paths/payment_intents@{id}@payments.yaml
- add: update checkout api
- add: note to use checkouts instead of payment intents
> add update checkout

- openapi/multi-yaml/components/schemas/BusinessResponse.yaml
ref: https://github.com/justifi-tech/entity_management/issues/154
> Business API with terms_conditions_accepted

- openapi/multi-yaml/components/schemas/BusinessResponse.yaml
- openapi/multi-yaml/paths/entities_business.yaml
https://github.com/justifi-tech/entity_management/issues/142
> Include Business classification in API docs

- openapi/docs/events.md
- openapi/multi-yaml/components/schemas/PayoutSetting.yaml
- openapi/multi-yaml/events/account_payout_setting_updated.yaml
- openapi/multi-yaml/index.yaml
- feat: PayoutSetting schema
- account.payout_setting.updated event
> 1278 account payout setting event

- openapi/multi-yaml/paths/entities_provisioning.yaml
Issue https://github.com/justifi-tech/entity_management/issues/171
> Remove new_account_name from provisioining API

- openapi/multi-yaml/components/schemas/Checkout.yaml
- openapi/multi-yaml/paths/checkouts@{id}.yaml
> Fix missing Checkout API response

- openapi/multi-yaml/components/schemas/Checkout.yaml
- openapi/multi-yaml/paths/checkouts.yaml
- openapi/multi-yaml/paths/checkouts@{id}.yaml
- chore: checkout with application fees and stmt desc
- chore: update checkout response with app fees and stmt desc
> api-docs: checkout with application_fees and stmt_descriptor

- openapi/multi-yaml/components/schemas/BankAccountResponse.yaml
- openapi/multi-yaml/components/schemas/IdentityResponse.yaml
Ref: https://github.com/justifi-tech/entity_management/issues/181
> Docs: note about ssn_last4 and fix account_number_last4

- openapi/multi-yaml/components/schemas/Terminal.yaml
- openapi/multi-yaml/paths/entities_business.yaml
- **chore: add missing terminal attributes**
- **chore: remove incorrect info from business owners**
> Add missing terminal attributes

- openapi/docs/onboarding.md
- openapi/multi-yaml/index.yaml
- Add onboarding via component walkthrough
- Update sub accounts intro and add onboarding via component link
> 98 onboarding via component

- openapi/multi-yaml/components/schemas/PaymentMethodGroupResponse.yaml
- openapi/multi-yaml/components/schemas/SubAccountSettings.yaml
- openapi/multi-yaml/index.yaml
- feat: add platform_account_id to payment_method_group response
- feat: document Platform Wallet Accounts feature
> 102 api docs document feature and enable for lessonscom

- openapi/multi-yaml/components/schemas/BankAccount.yaml
- openapi/multi-yaml/components/schemas/CreateBankAccount.yaml
- **fix: bank account example**
- **fix: missing create bank account param**
Closes #109
> Bank Account parameters mismatch

- openapi/multi-yaml/components/schemas/DisputeEvidence.yaml
- openapi/multi-yaml/components/schemas/DisputeResponse.yaml
- openapi/multi-yaml/events/dispute_evidence.yaml
- openapi/multi-yaml/events/disputes.yaml
- openapi/multi-yaml/index.yaml
- openapi/multi-yaml/paths/disputes@{id}@evidence.yaml
- openapi/multi-yaml/paths/disputes@{id}@response.yaml
Closes https://github.com/justifi-tech/public-docs/issues/107
> Documentation and cs handover

- openapi/multi-yaml/paths/checkouts.yaml
> Fix list checkout missing data response

- openapi/multi-yaml/components/schemas/Terminal.yaml
- openapi/multi-yaml/paths/terminals@{id}.yaml
https://github.com/justifi-tech/hosted-checkout-be/issues/474
> Terminal update nickname

- openapi/multi-yaml/components/parameters/financial-transaction-id.yaml
- openapi/multi-yaml/paths/payments.yaml
- rm financial-transaction-id query param file
- rm: financial_transaction_id payments list parameter
> 118 rm remove financial transaction id from api docs

- openapi/multi-yaml/paths/terminals.yaml
https://github.com/justifi-tech/hosted-checkout-be/pull/485
Closes #121
> 121: Add terminal list query parameters

- openapi/multi-yaml/components/schemas/Dispute.yaml
Issue: https://github.com/justifi-tech/lambdas/issues/118
> Add account_id to dispute response

- openapi/docs/tokenize.md
Cose https://github.com/justifi-tech/public-docs/issues/125
> feat: update guide to use updated web component

- openapi/docs/events.md
- openapi/multi-yaml/components/schemas/PaymentSetting.yaml
- openapi/multi-yaml/components/schemas/PayoutSetting.yaml
- openapi/multi-yaml/components/schemas/SubAccountSettings.yaml
- openapi/multi-yaml/events/account_payment_setting_updated.yaml
- openapi/multi-yaml/index.yaml
- feat: add PaymentSetting
- feat: update PayoutSetting and use in SubAccountSettings
- feat: add account.payment_setting.updated event
Links:
https://github.com/justifi-tech/capital/issues/1560
Related prs:
https://github.com/justifi-tech/account_settings/pull/295
https://github.com/justifi-tech/capital/pull/1585
https://github.com/justifi-tech/customer-admin-fe/pull/500
> 1560 add account payment setting event

- openapi/multi-yaml/components/schemas/TerminalsOrder.yaml
- openapi/multi-yaml/paths/terminals_orders.yaml
- package.json
- pnpm-lock.yaml
- **chore: update docusaurus dependencies**
- **feat: add terminal order statuses and filters**
Closes #132
> 132: Update terminal order status

- openapi/multi-yaml/components/schemas/TerminalsOrder.yaml
Issue: https://github.com/justifi-tech/hosted-checkout-be/issues/798
> Add business name to terminal order apis

- openapi/multi-yaml/paths/terminals_orders.yaml
- openapi/multi-yaml/paths/terminals_orders@{id}.yaml
https://github.com/justifi-tech/engineering-artifacts/issues/113
> Live terminal order API

- docs/checkouts/lifecycle.mdx
- openapi/multi-yaml/components/schemas/BankAccountPayment.yaml
- openapi/multi-yaml/components/schemas/BusinessResponse.yaml
- openapi/multi-yaml/components/schemas/CardPayment.yaml
- openapi/multi-yaml/components/schemas/CardPaymentWithEnvelope.yaml
- openapi/multi-yaml/components/schemas/Checkout.yaml
- openapi/multi-yaml/components/schemas/CheckoutCompletion.yaml
- openapi/multi-yaml/components/schemas/CheckoutCompletionAttempt.yaml
- openapi/multi-yaml/components/schemas/Envelope.yaml
- openapi/multi-yaml/components/schemas/TransactionHold.yaml
- openapi/multi-yaml/events/payments.yaml
- openapi/multi-yaml/paths/payments.yaml
- openapi/multi-yaml/paths/payments@{id}.yaml
- openapi/multi-yaml/paths/payments@{id}@capture.yaml
- feat: add missing properties to checkout
- chore: update checkout completion
- chore: update id property in envelope
- chore: add example to associated_accounts in business
- feat: add missing attributes to payment response
- feat: add payment response to checkout completion
> 191 update checkout api response

- openapi/docs/events.md
- openapi/multi-yaml/events/terminal_orders.yaml
- openapi/multi-yaml/index.yaml
https://github.com/justifi-tech/engineering-artifacts/issues/203
> Add terminal order events

- openapi/multi-yaml/components/schemas/Terminal.yaml
- openapi/multi-yaml/paths/terminals.yaml
- feat: add missing properties to terminal schema
- feat: add missing query params to list terminals
- chore: update descriptions
> 238 add provider id filter to list terminals

- openapi/docs/description.md
https://github.com/justifi-tech/engineering-artifacts/issues/502
> 502: Refactor error messages

- openapi/multi-yaml/components/schemas/PaymentError.yaml
- openapi/multi-yaml/paths/payments.yaml
Closes https://github.com/justifi-tech/engineering-artifacts/issues/492
> 492: Document 402 payment error response

- openapi/multi-yaml/components/schemas/Report.yaml
- openapi/multi-yaml/components/schemas/ReportInterchangeFeeParameters.yaml
- openapi/multi-yaml/components/schemas/ReportPaymentListParameters.yaml
- openapi/multi-yaml/components/schemas/ReportPayoutParameters.yaml
- openapi/multi-yaml/components/schemas/ReportProceedsParameters.yaml
- openapi/multi-yaml/components/schemas/ReportSubAccountSummaryParameters.yaml
- openapi/multi-yaml/paths/reports.yaml
https://github.com/justifi-tech/engineering-artifacts/issues/598
> 598: Add nickname to reports api

- openapi/multi-yaml/components/schemas/Checkout.yaml
https://github.com/justifi-tech/engineering-artifacts/issues/821
> Add bank_account_verification to payment_settings

- openapi/multi-yaml/components/schemas/BusinessResponse.yaml
- openapi/multi-yaml/components/schemas/EntityBankAccount.yaml
- openapi/multi-yaml/paths/entities_bank_accounts.yaml
- openapi/multi-yaml/paths/entities_business.yaml
- openapi/multi-yaml/paths/entities_business@{id}.yaml
> Fixing the enums to be individual and not a single enum

- openapi/multi-yaml/components/schemas/BusinessResponse.yaml
- openapi/multi-yaml/paths/entities_business.yaml
- openapi/multi-yaml/paths/entities_business@{id}.yaml
> 878: Add business tax id last4

- openapi/multi-yaml/components/schemas/Checkout.yaml
- openapi/multi-yaml/paths/checkouts.yaml
- openapi/multi-yaml/paths/checkouts@{id}.yaml
https://github.com/justifi-tech/engineering-artifacts/issues/875
> Add metadata to Checkout docs
